baseURL = 'https://srgsanky.github.io/rusty-treasures/'
languageCode = 'en-us'
title = 'Rusty Treasures'
theme = 'hugo-dead-simple'

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true
